---
title: "Untitled"
output: html_document
date: "2022-11-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
### Data Import
knitr::opts_knit$set(root.dir = 'C:/Users/Surface/Downloads/Client')
# For getting data
library(readxl)
# For getting map data
library(ggmap)
# For modifying data
library(dplyr)
```

```{r}
getwd()
list.files()
register_google(key = "AIzaSyDr_n8-ZBHTHzyca-P3LnMiSCtYn2sVTkI")
```

```{r}
### 2020
## Data Cleaning
Data20 <- read_excel("2020 Client List.xls")
Data20_Clean <- Data20 %>%
  select(CustomerType,
         PhysicalCity, 
         Longitude, 
         Latitude)
# Moorhead Data
Data20_M <- Data20_Clean %>%
  filter(PhysicalCity == "Moorhead")%>%
  select(CustomerType, 
         Longitude, 
         Latitude)
lo <- c(as.numeric(unlist(Data20_M[, "Longitude"])))
str <- c("5th", "8th","11th","14th","17th","20th","Main","34th", "40th","45th")

la <- c(as.numeric(unlist(Data20_M[, "Latitude"])))
ave <- c("28 A.N", "15 A.N", "7 A.N", "4 A.N", "Main", "5 A.S", "12 A.S", "20 A.S", "24 A.S", "I.94", "30 A.S", "40 A.S", "46 A.S", "50 A.S", "60 A.S")

#----------------------------------------------------
long_str <- c(-96.77247,-96.76793,-96.76272,-96.75744,-96.75319, -96.74782,-96.739125,-96.725256,-96.715021,-96.70444)
zone_ver <- c(1:(length(str)+1))
zone_vertical <- c()
for (x in lo){
  for (y in long_str){
    if (x < y){
      p <- which(long_str == y)
      break
    }
    if (x < min(long_str)){
      p <- length(long_str) + 1
    }
  }
  zone_vertical <- c(zone_vertical, p)
}
Data20_M <- cbind(Data20_M, zone_vertical)

#----------------------------------------------------
lat_ave <- c(46.905086, 46.890692,46.883114,46.879259,46.873759, 46.869303, 46.862142, 46.854969, 46.851394, 46.846959, 46.844069, 46.833061, 46.825732, 46.818389, 46.803880)
zone_horizontal <- c(letters[1:length(lat_ave)])
zone_hori <- c()
for (x in la){
  for (y in lat_ave){
    if (x > y){
      p <- which(lat_ave == y)
      break
    }
    if (x > max(lat_ave)){
      p <- length(lat_ave) + 1
    }
  }
  p <- zone_horizontal[p]
  zone_hori <- c(zone_hori, p)
}
Data20_M <- cbind(Data20_M, zone_hori)

Data20_M$Concatenated <- paste(Data20_M$zone_vertical, Data20_M$zone_hori)
Zone <- c(Data20_M$Concatenated)
Data20_M <- Data20_M%>%
  select(Longitude, Latitude)
Data20_M <- cbind(Data20_M, Zone)
Data20_M

#----------------------------------------------------
```
```{r}
zone_names <- c()
for (x in zone_ver){
  for (y in zone_horizontal){
    zone <- paste(x,y)
    zone_names <- c(zone_names, zone)
  }
}

n_house <- c()
for (x in zone_names){
n <- Data20_M %>%
  filter(Zone == x)
n_house <- c(n_house, nrow(n))
}

Counting <- as_tibble(cbind(zone_names, n_house))
Counting
```
