---
title: "Code_Moorhead"
output: html_document
date: "2022-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
### Data Import
knitr::opts_knit$set(root.dir = 'C:/Users/Surface/Downloads/Client')
## Loading libraries
# For getting data
library(readxl)
# For modifying data
library(dplyr)
# For getting map data
library(ggmap)
# For getting streets data
library(osmdata)
# For Encode Spatial Data
library(sf)
# For Mapping
library(mapview)
```

```{r}
### Setting up
getwd()
list.files()
register_google(key = "#Insert API here"")
```
```{r}
### Data Cleaning
## 2018
Data18 <- read_excel("2018 Client List.xls")
Data18_Clean <- Data18 %>%
  select(CustomerType,
         PhysicalCity, 
         Longitude, 
         Latitude)
# Moorhead Data
Data18_M <- Data18_Clean %>%
  filter(PhysicalCity == "Moorhead")%>%
  select(CustomerType, 
         Longitude, 
         Latitude)
Data18_M_New <- Data18_M %>%
  filter(CustomerType == "Client")
Data18_M_Old <- Data18_M %>%
  filter(CustomerType == "FormerClient")
# Mapping 
Addr18_M <- st_as_sf(Data18_M, 
                     coords = c("Longitude", "Latitude"), 
                     crs = 4326)

## 2019
Data19 <- read_excel("2019 Client List.xls")
Data19_Clean <- Data19 %>%
  select(CustomerType,
         PhysicalCity, 
         Longitude, 
         Latitude)
# Moorhead Data
Data19_M <- Data19_Clean %>%
  filter(PhysicalCity == "Moorhead")%>%
  select(CustomerType, 
         Longitude, 
         Latitude)
Data19_M_New <- Data19_M %>%
  filter(CustomerType == "Client")
Data19_M_Old <- Data19_M %>%
  filter(CustomerType == "FormerClient")
# Mapping 
Addr19_M <- st_as_sf(Data19_M, 
                     coords = c("Longitude", "Latitude"), 
                     crs = 4326)

## 2020
Data20 <- read_excel("2020 Client List.xls")
Data20_Clean <- Data20 %>%
  select(CustomerType,
         PhysicalCity, 
         Longitude, 
         Latitude)
# Moorhead Data
Data20_M <- Data20_Clean %>%
  filter(PhysicalCity == "Moorhead")%>%
  select(CustomerType, 
         Longitude, 
         Latitude)
Data20_M_New <- Data20_M %>%
  filter(CustomerType == "Client")
Data20_M_Old <- Data20_M %>%
  filter(CustomerType == "FormerClient")
# Mapping 
Addr20_M <- st_as_sf(Data20_M, 
                     coords = c("Longitude", "Latitude"), 
                     crs = 4326)

## 2021
Data21 <- read_excel("2021 Client List.xls")
Data21_Clean <- Data21 %>%
  select(CustomerType,
         PhysicalCity, 
         Longitude, 
         Latitude)
# Moorhead Data
Data21_M <- Data21_Clean %>%
  filter(PhysicalCity == "Moorhead")%>%
  select(CustomerType, 
         Longitude, 
         Latitude)
Data21_M_New <- Data21_M %>%
  filter(CustomerType == "Client")
Data21_M_Old <- Data21_M %>%
  filter(CustomerType == "FormerClient")
# Mapping 
Addr21_M <- st_as_sf(Data21_M, 
                     coords = c("Longitude", "Latitude"), 
                     crs = 4326)

## 2022
Data22 <- read_excel("2022 Client List.xlsx")
Data22_Clean <- Data22 %>%
  select(CustomerType,
         PhysicalCity, 
         Longitude, 
         Latitude)
# Moorhead Data
Data22_M <- Data22_Clean %>%
  filter(PhysicalCity == "Moorhead")%>%
  select(CustomerType, 
         Longitude, 
         Latitude)
Data22_M_New <- Data22_M %>%
  filter(CustomerType == "Client")
Data22_M_Old <- Data22_M %>%
  filter(CustomerType == "FormerClient")
## Mapping 
Addr22_M <- st_as_sf(Data22_M, 
                     coords = c("Longitude", "Latitude"), 
                     crs = 4326)

### Streets data
M_streets <- getbb("Moorhead Minnesota")%>%
  opq()%>%
  add_osm_feature(key = "highway", 
                  value = c("motorway", "primary","secondary", "tertiary", "residential" )) %>%
  osmdata_sf()
mapview(M_streets[["osm_lines"]]) + mapview(Addr20_M )
```
```{r}
### 2023 Data Prediction 
## Return Rate # Maybe not needed
# Previous Years
return_r19_M <- nrow(Data19_M_Old)/nrow(Data18_M)
return_r20_M <- nrow(Data20_M_Old)/nrow(Data19_M)
return_r21_M <- nrow(Data21_M_Old)/nrow(Data20_M)
return_r22_M <- nrow(Data22_M_Old)/nrow(Data21_M)
# Expected Return Rate
exp_r_r_M <- mean(c(return_r19_M, return_r20_M, return_r21_M, return_r22_M))
# Random Return Clients
return_M <- sample_n(Data20_M, round(exp_r_r_M*nrow(Data20_M)))
# Mapping Return Clients
Addr_Return_M <- st_as_sf(return_M, 
                     coords = c("Longitude", "Latitude"), 
                     crs = 4326)

## Growth Rate
# Previous Years
grow_r19_M <- nrow(Data19_M)/nrow(Data18_M)
grow_r20_M <- nrow(Data20_M)/nrow(Data19_M)
grow_r21_M <- nrow(Data21_M)/nrow(Data20_M)
grow_r22_M <- nrow(Data22_M)/nrow(Data21_M)
# Expected Growth Rate
exp_g_r_M <- mean(c(grow_r19_M, grow_r20_M, grow_r21_M, grow_r22_M))
# Expected Number of New Clients
n_new_M <- round((exp_g_r_M)*nrow(Data22_M))
# Expected New Clients
New23_M <- rbind(Data18_M, Data19_M,Data20_M)
New23_M <- sample_n(Data20_M, n_new_M)
# Mapping New Clients
Addr_New_M <- st_as_sf(New23_M, 
                     coords = c("Longitude", "Latitude"), 
                     crs = 4326)

## 2023 Expected Mapping
mapview(Addr_New_M) + mapview(M_streets[["osm_lines"]])

```

